# Generated by Django 4.1.1 on 2022-09-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0011_remove_about_background_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(choices=[(0, 'Legal advice'), (1, 'Starting Business')], default=0)),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_ja', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='service/images/')),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ja', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background')),
                ('background_ja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background')),
                ('background_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background')),
            ],
        ),
    ]
