# Generated by Django 4.1.1 on 2022-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.IntegerField(choices=[(0, 'None')], default=0)),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'NEW'), (1, 'PROCESS'), (2, 'CANCELED'), (3, 'FINISHED')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Let's talk",
                'verbose_name_plural': "1. Let's talk",
            },
        ),
    ]
