# Generated by Django 4.1.1 on 2022-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'New')], default=0),
        ),
    ]
