# Generated by Django 4.1.1 on 2022-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'University'), (2, 'Work'), (3, 'Study'), (4, 'Order')], default=0),
        ),
    ]
