# Generated by Django 4.1.1 on 2022-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_category_options_alter_study_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyblog',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studyblog',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studyblog',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyblog',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
