# Generated by Django 4.1.1 on 2022-09-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_category_title_ja_category_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityimages',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_images', to='study.university'),
        ),
    ]
