# Generated by Django 4.1.1 on 2022-10-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_about_background_en_and_more'),
        ('study', '0006_remove_study_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='background_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background'),
        ),
        migrations.AddField(
            model_name='study',
            name='background_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background'),
        ),
    ]
