# Generated by Django 4.1.1 on 2022-09-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('background', models.ImageField(upload_to='background/', verbose_name='Background')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': '1. Background',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Brand title')),
                ('image', models.ImageField(upload_to='', verbose_name='brand/image/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': '4. Brand',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Article title')),
                ('image', models.ImageField(null=True, upload_to='company/article-image/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': '2. Article',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='About title')),
                ('image', models.ImageField(null=True, upload_to='about/image/', verbose_name='Image')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background')),
            ],
            options={
                'verbose_name': 'About company',
                'verbose_name_plural': '3. About company',
            },
        ),
    ]
