# Generated by Django 4.1.1 on 2022-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_article_options_alter_background_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='lang',
        ),
        migrations.AddField(
            model_name='background',
            name='status',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'TOP'), (2, 'MIDDLE'), (3, 'BOTTOM')], default=0),
        ),
    ]
