# Generated by Django 4.1.1 on 2022-09-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_about_description_en_about_description_jp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description_jp',
            new_name='description_jpn',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title_jp',
            new_name='title_jpn',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description_jp',
            new_name='description_jpn',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title_jp',
            new_name='title_jpn',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='title_jp',
            new_name='title_jpn',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='title_jp',
            new_name='title_jpn',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='description_jp',
            new_name='description_jpn',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='title_jp',
            new_name='title_jpn',
        ),
    ]
