# Generated by Django 4.1.1 on 2022-09-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_description_jp_about_description_jpn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description_jpn',
            new_name='description_ja',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title_jpn',
            new_name='title_ja',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description_jpn',
            new_name='description_ja',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title_jpn',
            new_name='title_ja',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='title_jpn',
            new_name='title_ja',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='title_jpn',
            new_name='title_ja',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='description_jpn',
            new_name='description_ja',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='title_jpn',
            new_name='title_ja',
        ),
    ]
