# Generated by Django 4.1.1 on 2022-09-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_background_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='background_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='background_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='title_en',
        ),
    ]
