# Generated by Django 4.1.1 on 2022-09-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0011_remove_about_background_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAndVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='miss_vis/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background')),
            ],
        ),
    ]
