# Generated by Django 4.1.1 on 2022-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_vision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionandvision',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='missionandvision',
            name='background',
        ),
        migrations.AlterField(
            model_name='missionandvision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
