# Generated by Django 4.1.1 on 2022-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_vision', '0002_rename_message_missionandvision_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionandvision',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='missionandvision',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='missionandvision',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missionandvision',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
