# Generated by Django 4.1.1 on 2022-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='9 ta raqam bolishi kerak, masalan: 979998877', max_length=9, null=True, unique=True, verbose_name='Raqami*'),
        ),
    ]
