# Generated by Django 4.1.1 on 2022-09-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expertise Levels',
                'verbose_name_plural': '5. Expertise Levels',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Frameworks',
                'verbose_name_plural': '4. Frameworks',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='work/jobs/icons')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job types',
                'verbose_name_plural': '1. Jop types',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programming Languages',
                'verbose_name_plural': '2. Programming Languages',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Specialties',
                'verbose_name_plural': '3. Specialties',
            },
        ),
        migrations.CreateModel(
            name='WorkingConditionAndBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Working Conditions and Benefits',
                'verbose_name_plural': '6. Working Conditions and Benefits',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='work/images/')),
                ('background_image', models.ImageField(upload_to='work/backgrounds/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('salary', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expertise_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.expertiselevel')),
                ('frameworks', models.ManyToManyField(to='work.framework')),
                ('jop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.jobtype')),
                ('programming_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.programminglanguages')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.specialty')),
                ('working_conditions_and_benefits', models.ManyToManyField(to='work.workingconditionandbenefit')),
            ],
            options={
                'verbose_name': 'Jobs',
                'verbose_name_plural': '7. Jobs',
            },
        ),
    ]
