# Generated by Django 4.1.1 on 2022-09-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_article_options_alter_background_options_and_more'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': '1.0. Categories'},
        ),
        migrations.AlterModelOptions(
            name='expertiselevel',
            options={'verbose_name': 'Expertise Levels', 'verbose_name_plural': '2.4. Expertise Levels'},
        ),
        migrations.AlterModelOptions(
            name='framework',
            options={'verbose_name': 'Frameworks', 'verbose_name_plural': '2.3. Frameworks'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Jobs', 'verbose_name_plural': '2.6. Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Job types', 'verbose_name_plural': '2.0. Jop types'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguages',
            options={'verbose_name': 'Programming Languages', 'verbose_name_plural': '2.1. Programming Languages'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialties', 'verbose_name_plural': '2.2. Specialties'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Works', 'verbose_name_plural': '1.1. Works'},
        ),
        migrations.AlterModelOptions(
            name='workingconditionandbenefit',
            options={'verbose_name': 'Working Conditions and Benefits', 'verbose_name_plural': '2.5. Working Conditions and Benefits'},
        ),
        migrations.RemoveField(
            model_name='work',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.RemoveField(
            model_name='work',
            name='created_at',
        ),
        migrations.AddField(
            model_name='work',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.background'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expertise_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertise_level', to='work.expertiselevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='frameworks',
            field=models.ManyToManyField(related_name='frameworks', to='work.framework'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jop_type', to='work.jobtype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='programming_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programming_language', to='work.programminglanguages'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(help_text='For example ($2500 - 3000 / month)', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speciality', to='work.specialty'),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_conditions_and_benefits',
            field=models.ManyToManyField(related_name='working_conditions_and_benefits', to='work.workingconditionandbenefit'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='work/images'),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='work/visa/images/')),
                ('background_image', models.ImageField(upload_to='work/backgrounds/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.category')),
            ],
            options={
                'verbose_name': 'Visas',
                'verbose_name_plural': '1.1. Visas',
            },
        ),
    ]
