# Generated by Django 4.1.1 on 2022-10-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_about_background_en_and_more'),
        ('work', '0005_work_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_ja', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='work/visa/images/')),
                ('background_image', models.ImageField(upload_to='work/backgrounds/')),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ja', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
                ('background_ja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
                ('background_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
            ],
            options={
                'verbose_name': 'Visas',
                'verbose_name_plural': '1.2. Visas',
            },
        ),
        migrations.CreateModel(
            name='WorkVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_ja', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='work/visa/images/')),
                ('background_image', models.ImageField(upload_to='work/backgrounds/')),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ja', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
                ('background_ja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
                ('background_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.background')),
            ],
            options={
                'verbose_name': 'Visas',
                'verbose_name_plural': '1.2. Visas',
            },
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
    ]
